FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
COPY apps/web/package.json ./apps/web/package.json

RUN npm install

COPY apps ./apps
COPY configs ./configs

CMD ["npm", "run", "dev:web"]
